apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwk-mooc-project-pv # name of the persistent volume, this will be used in the persistent volume claim
  namespace: project # namespace where the persistent volume is created, this should match the namespace of the persistent volume claim
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete # this means that the persistent volume will be deleted when the persistent volume claim is deleted
  storageClassName: ""
  csi:
    driver: driver.longhorn.io
    volumeHandle: dwk-project-persistence
    fsType: ext4
